//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Higgs.Mbale.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuveraCategory
    {
        public BuveraCategory()
        {
            this.Buveras = new HashSet<Buvera>();
        }
    
        public long BuveraCategoryId { get; set; }
        public string Name { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<Buvera> Buveras { get; set; }
    }
}
