//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Higgs.Mbale.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequistionSupply
    {
        public long RequistionId { get; set; }
        public long SupplyId { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual Requistion Requistion { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
