//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Higgs.Mbale.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequistionCategory
    {
        public RequistionCategory()
        {
            this.Cashes = new HashSet<Cash>();
            this.Requistions = new HashSet<Requistion>();
        }
    
        public long RequistionCategoryId { get; set; }
        public string Name { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual ICollection<Cash> Cashes { get; set; }
        public virtual ICollection<Requistion> Requistions { get; set; }
    }
}
