//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Higgs.Mbale.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightNoteRange
    {
        public WeightNoteRange()
        {
            this.WeightNoteNumbers = new HashSet<WeightNoteNumber>();
        }
    
        public long WeightNoteRangeId { get; set; }
        public double StartNumber { get; set; }
        public double EndNumber { get; set; }
        public long BranchId { get; set; }
        public bool Printed { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual ICollection<WeightNoteNumber> WeightNoteNumbers { get; set; }
    }
}
